module DownstreamTests
using Pkg
using Test

const TEST_DIR = @__DIR__
const UTILS_PATH = joinpath(TEST_DIR, "utils.jl")
const REMOVE_TMP_FILES = true

function print_centered_with_hash(s::String, n::Int)
    @assert n > 4 + length(s)

    total_padding = n - 4 - length(s)
    left_padding = div(total_padding, 2)
    right_padding = total_padding - left_padding

    centered = "##" * " "^left_padding * s * " "^right_padding * "##"

    println(repeat("#", n))
    println(repeat("#", n))
    println("##" * " "^(n - 4) * "##")
    println(centered)
    println("##" * " "^(n - 4) * "##")
    println(repeat("#", n))
    println(repeat("#", n))
end

function run()
    Pkg.activate(TEST_DIR)
    Pkg.instantiate()

    has_custom_bcube_branch =
        haskey(ENV, "BCUBE_BRANCH") && !isempty(strip(ENV["BCUBE_BRANCH"]))
    custom_bcube_branch = if has_custom_bcube_branch
        branch = strip(get(ENV, "BCUBE_BRANCH", "main"))
        @info "Running tests with custom Bcube branch '$branch'"
        branch
    else
        nothing
    end
    has_custom_bcubevtk_branch =
        haskey(ENV, "BCUBEVTK_BRANCH") && !isempty(strip(ENV["BCUBEVTK_BRANCH"]))
    custom_bcubevtk_branch = if has_custom_bcubevtk_branch
        branch = strip(get(ENV, "BCUBEVTK_BRANCH", "main"))
        @info "Running tests with custom BcubeVTK branch '$branch'"
        branch
    else
        nothing
    end
    has_custom_bcubegmsh_branch =
        haskey(ENV, "BCUBEGMSH_BRANCH") && !isempty(strip(ENV["BCUBEGMSH_BRANCH"]))
    custom_bcubegmsh_branch = if has_custom_bcubegmsh_branch
        branch = strip(get(ENV, "BCUBEGMSH_BRANCH", "main"))
        @info "Running tests with custom BcubeGmsh branch '$branch'"
        branch
    else
        nothing
    end

    SRC_DIR = joinpath(@__DIR__, "..", "example")
    filepaths = (
        joinpath(
            SRC_DIR,
            "linear_transport_diffeq",
            "linear_transport_single_par_diffeq.jl",
        ),
        # joinpath(SRC_DIR, "euler_cylinder_steady", "euler_cylinder_steady_par.jl"),
    )

    @testset "Examples" begin
        for filepath in filepaths
            dir = dirname(filepath)
            filename = basename(filepath)
            tmp_filepath = joinpath(dir, "tester.jl")
            results_path = joinpath(dir, "results.csv")

            # Rq: use of `repr` to ensure path are OK on Windows (otherwise \\ are escaped)
            text = """
    # This file is automatically generated
    module Tester
    using Test
    using Pkg
    using ReferenceTests

    include($(repr(UTILS_PATH)))

    ENV["TestMode"] = "true"
    #ENV["JULIA_PKG_PRECOMPILE_AUTO"] = 0

    Pkg.activate($(repr(dir)))
    pkgSpec = Pkg.PackageSpec[]
    $has_custom_bcube_branch && push!(pkgSpec, Pkg.PackageSpec(; name = "Bcube", rev = $(repr(custom_bcube_branch))))
    $has_custom_bcubevtk_branch && push!(pkgSpec, Pkg.PackageSpec(; name = "BcubeVTK", rev = $(repr(custom_bcubevtk_branch))))
    $has_custom_bcubegmsh_branch && push!(pkgSpec, Pkg.PackageSpec(; name = "BcubeGmsh", rev = $(repr(custom_bcubegmsh_branch))))
    (length(pkgSpec) > 0) && Pkg.add(pkgSpec)
    Pkg.instantiate(verbose=false)

    run_mpi(; nprocs = 3, filepath = $filepath)

    end
    """
            open(tmp_filepath, "w") do f
                print(f, text)
            end

            @testset "$filename" begin
                # Display
                print_centered_with_hash("Running case $filename", 80)

                # Run the julia script
                cmd = `julia --startup-file=no --project=$TEST_DIR $(tmp_filepath)`
                try
                    run(cmd)
                catch e
                    REMOVE_TMP_FILES && rm(tmp_filepath)
                    throw(e)
                end
                REMOVE_TMP_FILES && rm(tmp_filepath)

                # Check the results
                if isfile(results_path)
                    lines = readlines(results_path)
                    line = split(lines[2], ',')
                    passes, errors, fails, broken = parse.(Int, line)

                    # Check that at least one test did run
                    # So that we can display "Total = 0" if no test are present
                    if passes + errors + fails + broken > 0
                        @test errors == fails == broken == 0
                    end

                    REMOVE_TMP_FILES && rm(results_path)
                else
                    error("Missing result file")
                end
            end
        end
    end
end

end